#!/bin/sh

copy -f ico-astronavi.png ico-astronavi-8472.png
copy -f ico-astronavi.png ico-astronavi-breen.png
copy -f ico-astronavi.png ico-astronavi-tellar.png
copy -f ico-astronavi.png ico-astronavi-varie.png
copy -f ico-astronavi-bajor.png ico-astronavi-bajor-antares.png
copy -f ico-astronavi-bajor.png ico-astronavi-bajor-vela.png
copy -f ico-astronavi-borg.png ico-astronavi-borg-cubi.png
copy -f ico-astronavi-borg.png ico-astronavi-borg-sfere.png
copy -f ico-astronavi-cardassia.png ico-astronavi-cardassia-galor.png
copy -f ico-astronavi-cardassia.png ico-astronavi-cardassia-hideki.png
copy -f ico-astronavi-cardassia.png ico-astronavi-cardassia-kelon.png
copy -f ico-astronavi-dominio.png ico-astronavi-dominio-battaglia.png
copy -f ico-astronavi-dominio.png ico-astronavi-dominio-caccia.png
copy -f ico-astronavi-dominio.png ico-astronavi-dominio-incrociatore.png
copy -f ico-astronavi-ferengi.png ico-astronavi-ferengi-dkora.png
copy -f ico-astronavi-ferengi.png ico-astronavi-ferengi-pod.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-akira.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-ambassador.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-andromeda.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-antares.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-apollo.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-bradbury.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-centaur.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-challenger.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-chimera.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-constellation.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-constitution.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-daedalus.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-danube.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-defiant.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-deneva.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-excelsior.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-freedom.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-galaxy.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-hokulea.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-intrepid.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-istanbul.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-iv.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-korolev.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-mediterranean.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-merced.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-miranda.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-nar.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-nebula.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-neworleans.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-niagara.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-norway.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-nova.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-nx.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-oberth.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-olympic.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-peregrine.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-prometheus.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-renaissance.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-rigel.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-saber.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-sequoia.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-6.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-7.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-8.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-9.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-10.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-11.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-15.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-angolare.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-defiant.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-ii.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-originale.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-pod.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-shuttle-vari.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-sovereign.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-soyuz.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-springfield.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-steamrunner.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-surak.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-sydney.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-venture.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-wambundu.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-wells.png
copy -f ico-astronavi-flottastellare.png ico-astronavi-flottastellare-yorkshire.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-brel.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-d5.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-d7.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-d12.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-ktinga.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-ktoch.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-kvort.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-neghvar.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-raptor.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-toron.png
copy -f ico-astronavi-klingon.png ico-astronavi-klingon-vorcha.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-bop2150.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-bop2260.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-d7.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-dderidex.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-scout.png
copy -f ico-astronavi-romulane.png ico-astronavi-romulane-warbird.png
copy -f ico-astronavi-terra.png ico-astronavi-terra-dy100.png
copy -f ico-astronavi-terra.png ico-astronavi-terra-dy500.png
copy -f ico-astronavi-terra.png ico-astronavi-terra-j.png
copy -f ico-astronavi-terra.png ico-astronavi-terra-y.png
copy -f ico-astronavi-ufp.png ico-astronavi-ufp-erewon.png
copy -f ico-astronavi-vulcano.png ico-astronavi-vulcano-sn.png
copy -f ico-astronavi-vulcano.png ico-astronavi-vulcano-suurok.png
copy -f ico-cast.png ico-cast-a.png
copy -f ico-cast.png ico-cast-b.png
copy -f ico-cast.png ico-cast-c.png
copy -f ico-cast.png ico-cast-d.png
copy -f ico-cast.png ico-cast-e.png
copy -f ico-cast.png ico-cast-f.png
copy -f ico-cast.png ico-cast-g.png
copy -f ico-cast.png ico-cast-h.png
copy -f ico-cast.png ico-cast-i.png
copy -f ico-cast.png ico-cast-j.png
copy -f ico-cast.png ico-cast-k.png
copy -f ico-cast.png ico-cast-l.png
copy -f ico-cast.png ico-cast-m.png
copy -f ico-cast.png ico-cast-n.png
copy -f ico-cast.png ico-cast-o.png
copy -f ico-cast.png ico-cast-p.png
copy -f ico-cast.png ico-cast-q.png
copy -f ico-cast.png ico-cast-r.png
copy -f ico-cast.png ico-cast-s.png
copy -f ico-cast.png ico-cast-t.png
copy -f ico-cast.png ico-cast-u.png
copy -f ico-cast.png ico-cast-v.png
copy -f ico-cast.png ico-cast-w.png
copy -f ico-cast.png ico-cast-x.png
copy -f ico-cast.png ico-cast-y.png
copy -f ico-cast.png ico-cast-z.png
copy -f ico-dsn.png ico-dsn-episodio.png
copy -f ico-dsn.png ico-dsn-produzione.png
copy -f ico-dsn.png ico-dsn-qv.png
copy -f ico-dsn.png ico-dsn-titoliita.png
copy -f ico-dsn.png ico-dsn-titoliori.png
copy -f ico-ent.png ico-ent-episodio.png
copy -f ico-ent.png ico-ent-produzione.png
copy -f ico-ent.png ico-ent-qv.png
copy -f ico-ent.png ico-ent-titoliita.png
copy -f ico-ent.png ico-ent-titoliori.png
copy -f ico-etc.png ico-etc-altrishow.png
copy -f ico-etc.png ico-etc-qv.png
copy -f ico-libri.png ico-libri-altri.png
copy -f ico-libri.png ico-libri-newfrontier.png
copy -f ico-libri.png ico-libri-nonfiction.png
copy -f ico-med.png ico-med-farmaci.png
copy -f ico-med.png ico-med-malattie.png
copy -f ico-med.png ico-med-procedure.png
copy -f ico-med.png ico-med-strumenti.png
copy -f ico-mirror.png ico-mirror-basistellari.png
copy -f ico-mirror.png ico-mirror-organizzazioni.png
copy -f ico-navigazione.png ico-navigazione-basistellari.png
copy -f ico-navigazione.png ico-navigazione-bevande.png
copy -f ico-navigazione.png ico-navigazione-cibi.png
copy -f ico-navigazione.png ico-navigazione-fenomeni.png
copy -f ico-navigazione.png ico-navigazione-giochi.png
copy -f ico-navigazione.png ico-navigazione-manufatti.png
copy -f ico-navigazione.png ico-navigazione-monete.png
copy -f ico-navigazione.png ico-navigazione-nebulose.png
copy -f ico-navigazione.png ico-navigazione-piante.png
copy -f ico-navigazione.png ico-navigazione-sistemistellari.png
copy -f ico-navigazione.png ico-navigazione-xenobestiario.png
copy -f ico-navigazione.png ico-navigazione-zone.png
copy -f ico-personaggi.png ico-personaggi-09.png
copy -f ico-personaggi.png ico-personaggi-a.png
copy -f ico-personaggi.png ico-personaggi-b.png
copy -f ico-personaggi.png ico-personaggi-c.png
copy -f ico-personaggi.png ico-personaggi-d.png
copy -f ico-personaggi.png ico-personaggi-e.png
copy -f ico-personaggi.png ico-personaggi-f.png
copy -f ico-personaggi.png ico-personaggi-g.png
copy -f ico-personaggi.png ico-personaggi-h.png
copy -f ico-personaggi.png ico-personaggi-i.png
copy -f ico-personaggi.png ico-personaggi-j.png
copy -f ico-personaggi.png ico-personaggi-k.png
copy -f ico-personaggi.png ico-personaggi-l.png
copy -f ico-personaggi.png ico-personaggi-m.png
copy -f ico-personaggi.png ico-personaggi-n.png
copy -f ico-personaggi.png ico-personaggi-o.png
copy -f ico-personaggi.png ico-personaggi-p.png
copy -f ico-personaggi.png ico-personaggi-q.png
copy -f ico-personaggi.png ico-personaggi-r.png
copy -f ico-personaggi.png ico-personaggi-s.png
copy -f ico-personaggi.png ico-personaggi-t.png
copy -f ico-personaggi.png ico-personaggi-u.png
copy -f ico-personaggi.png ico-personaggi-v.png
copy -f ico-personaggi.png ico-personaggi-w.png
copy -f ico-personaggi.png ico-personaggi-x.png
copy -f ico-personaggi.png ico-personaggi-y.png
copy -f ico-personaggi.png ico-personaggi-z.png
copy -f ico-personaggi.png ico-personaggi-sn.png
copy -f ico-pianeti.png ico-pianeti-09.png
copy -f ico-pianeti.png ico-pianeti-a.png
copy -f ico-pianeti.png ico-pianeti-b.png
copy -f ico-pianeti.png ico-pianeti-c.png
copy -f ico-pianeti.png ico-pianeti-d.png
copy -f ico-pianeti.png ico-pianeti-e.png
copy -f ico-pianeti.png ico-pianeti-f.png
copy -f ico-pianeti.png ico-pianeti-g.png
copy -f ico-pianeti.png ico-pianeti-h.png
copy -f ico-pianeti.png ico-pianeti-i.png
copy -f ico-pianeti.png ico-pianeti-j.png
copy -f ico-pianeti.png ico-pianeti-k.png
copy -f ico-pianeti.png ico-pianeti-l.png
copy -f ico-pianeti.png ico-pianeti-m.png
copy -f ico-pianeti.png ico-pianeti-n.png
copy -f ico-pianeti.png ico-pianeti-o.png
copy -f ico-pianeti.png ico-pianeti-p.png
copy -f ico-pianeti.png ico-pianeti-q.png
copy -f ico-pianeti.png ico-pianeti-r.png
copy -f ico-pianeti.png ico-pianeti-s.png
copy -f ico-pianeti.png ico-pianeti-t.png
copy -f ico-pianeti.png ico-pianeti-u.png
copy -f ico-pianeti.png ico-pianeti-v.png
copy -f ico-pianeti.png ico-pianeti-w.png
copy -f ico-pianeti.png ico-pianeti-x.png
copy -f ico-pianeti.png ico-pianeti-y.png
copy -f ico-pianeti.png ico-pianeti-z.png
copy -f ico-pianeti.png ico-pianeti-sn.png
copy -f ico-specie.png ico-specie-09.png
copy -f ico-specie.png ico-specie-a.png
copy -f ico-specie.png ico-specie-b.png
copy -f ico-specie.png ico-specie-c.png
copy -f ico-specie.png ico-specie-d.png
copy -f ico-specie.png ico-specie-e.png
copy -f ico-specie.png ico-specie-f.png
copy -f ico-specie.png ico-specie-g.png
copy -f ico-specie.png ico-specie-h.png
copy -f ico-specie.png ico-specie-i.png
copy -f ico-specie.png ico-specie-j.png
copy -f ico-specie.png ico-specie-k.png
copy -f ico-specie.png ico-specie-l.png
copy -f ico-specie.png ico-specie-m.png
copy -f ico-specie.png ico-specie-n.png
copy -f ico-specie.png ico-specie-o.png
copy -f ico-specie.png ico-specie-p.png
copy -f ico-specie.png ico-specie-q.png
copy -f ico-specie.png ico-specie-r.png
copy -f ico-specie.png ico-specie-s.png
copy -f ico-specie.png ico-specie-t.png
copy -f ico-specie.png ico-specie-u.png
copy -f ico-specie.png ico-specie-v.png
copy -f ico-specie.png ico-specie-w.png
copy -f ico-specie.png ico-specie-x.png
copy -f ico-specie.png ico-specie-y.png
copy -f ico-specie.png ico-specie-z.png
copy -f ico-specie.png ico-specie-altri.png
copy -f ico-starfleet.png ico-starfleet-direttive.png
copy -f ico-starfleet.png ico-starfleet-procedure.png
copy -f ico-starfleet.png ico-starfleet-uniformi.png
copy -f ico-tas.png ico-tas-episodio.png
copy -f ico-tas.png ico-tas-produzione.png
copy -f ico-tas.png ico-tas-titoliita.png
copy -f ico-tas.png ico-tas-titoliori.png
copy -f ico-tech.png ico-tech-armi.png
copy -f ico-tech.png ico-tech-materiali.png
copy -f ico-tech.png ico-tech-strumenti.png
copy -f ico-tech.png ico-tech-teletrasporto.png
copy -f ico-tech.png ico-tech-warp.png
copy -f ico-tng.png ico-tng-episodio.png
copy -f ico-tng.png ico-tng-produzione.png
copy -f ico-tng.png ico-tng-qv.png
copy -f ico-tng.png ico-tng-titoliita.png
copy -f ico-tng.png ico-tng-titoliori.png
copy -f ico-tos.png ico-tos-episodio.png
copy -f ico-tos.png ico-tos-produzione.png
copy -f ico-tos.png ico-tos-qv.png
copy -f ico-tos.png ico-tos-titoliita.png
copy -f ico-tos.png ico-tos-titoliori.png
copy -f ico-voy.png ico-voy-episodio.png
copy -f ico-voy.png ico-voy-produzione.png
copy -f ico-voy.png ico-voy-qv.png
copy -f ico-voy.png ico-voy-titoliita.png
copy -f ico-voy.png ico-voy-titoliori.png

chown 1000 *

